class FileNotFoundError(Exception): ...

class PathExistsError(Exception): ...

class InvalidPasswordError(Exception): ...

class PasswordNotEqualsError(Exception): ...

class CommandError(Exception): ...

class ChangePasswordException(Exception): ...
